[package]
name = "qubit-fs"
version = "0.2.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-fs"
description = "Pluggable filesystem abstraction for Rust"
homepage = "https://github.com/qubit-ltd/rs-fs"
documentation = "https://docs.rs/qubit-fs"
readme = "README.md"
keywords = ["filesystem", "storage", "spi", "path", "qubit"]
categories = ["filesystem", "rust-patterns"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/RUST_CODING_STYLE.md",
    "/RUST_CODING_STYLE.zh_CN.md",
    "/doc/**/user_guide*.md",
    "/examples/**",
    "/resources/**",
    "/src/**",
    "/tests/**",
]

[lib]
name = "qubit_fs"
doctest = true

[dependencies]
log = "0.4"
parking_lot = "0.12"
thiserror = "2.0"
url = "2.5"

qubit-io = "0.5"
qubit-spi = { path = "../rs-spi", version = "0.8" }
qubit-metadata = { path = "../rs-metadata", version = "0.6" }

[features]
default = []
registry-cache = ["dep:qubit-atomic"]

[dependencies.qubit-atomic]
version = "0.13"
optional = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
