[package]
name = "qubit-fs"
version = "0.2.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-fs"
description = "Provider-neutral synchronous and asynchronous filesystem abstraction for Rust"
homepage = "https://github.com/qubit-ltd/rs-fs"
documentation = "https://docs.rs/qubit-fs"
readme = "README.md"
keywords = ["filesystem", "storage", "spi", "path", "qubit"]
categories = ["filesystem", "rust-patterns"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/RUST_CODING_STYLE.md",
    "/RUST_CODING_STYLE.zh_CN.md",
    "/doc/file_system_design.zh_CN.md",
    "/doc/**/user_guide*.md",
    "/examples/**",
    "/resources/**",
    "/src/**",
    "/tests/**",
]

[lib]
name = "qubit_fs"
doctest = true

[dependencies]
fluent-uri = "0.4.1"
qubit-io = { path = "../rs-io", version = "0.14" }
qubit-redact = { path = "../rs-redact", version = "0.3" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
