[package]
name = "qubit-fs-documentation-examples"
version = "0.0.0"
edition = "2024"
rust-version = "1.94"
publish = false

[workspace]

[features]
default = ["async"]
async = []

[dependencies]
qubit-fs = { version = "0.2", features = ["async"] }
qubit-fs-local = ">=0.9, <1.0"
qubit-io = "0.17"
tempfile = "3"
